- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- pubspec.yaml
- Initial release.
- Remove typo from the Flutter world.
> Release 1.0.0

- .github/workflows/flutter-ci.yml
- .gitignore
- Makefile
- README.md
- codecov.yaml
- pubspec.lock
- pubspec.yaml
- scripts/codecov.sh
- Add Codecov settings.
- We can check the test coverage on Codecov.
> Add Codeov settings

- CHANGELOG.md
- pubspec.yaml
- Fix https://github.com/FlutterGen/flutter_gen/issues/21
> bump up 1.0.1

- README.md
- example/lib/gen/assets.gen.dart
- lib/src/generators/integrations/svg_integration.dart
- test_resources/actual_data/assets.gen.dart
- Fix insufficient params of flutter_svg.
- Pass CI.
> Fix flutter_svg params

- CHANGELOG.md
- pubspec.yaml
Bugfix
- Insufficient params of flutter_svg [#32](https://github.com/FlutterGen/flutter_gen/pull/34)
- Pass CI
> Release v1.0.3

- CHANGELOG.md
- example/.dart_tool/build/entrypoint/build.dart
- example/pubspec.lock
- example/pubspec.yaml
- pubspec.lock
- pubspec.yaml
New Feature
- [#33](https://github.com/FlutterGen/flutter_gen/pull/33) Support to generate flat hierarchy assets with field name style:
- camel-case
- snake-case
- Pass CI.
> Release v1.1.0

- CHANGELOG.md
- CONTRIBUTING.md
- example/pubspec.lock
- pubspec.yaml
New Feature
- [#40](https://github.com/FlutterGen/flutter_gen/pull/40) Support MaterialAccentColor
- Pass CI
> release 1.2.0

- lib/src/settings/flutter_gen.dart
- test/flutter_gen_test.dart
- test_resources/pubspec_change_output_path.yaml
- test_resources/pubspec_wrong_output_path.yaml
Fixed [#42](https://github.com/FlutterGen/flutter_gen/issues/42) 
Pass CI
> Fix checking output path

- CHANGELOG.md
- pubspec.yaml
Bug fix
- [#42](https://github.com/FlutterGen/flutter_gen/pull/42) Generated output folder name not being respected
Pass CI
> Release 1.2.1

- CHANGELOG.md
- example/pubspec.lock
- pubspec.yaml
- [#51](https://github.com/FlutterGen/flutter_gen/pull/51) Added support for Key parameter in image() and svg().
Pass CI.
> Release 1.2.2

- pubspec.yaml
> Fix pubspec.yaml homepage key

- CHANGELOG.md
- pubspec.yaml
Bugfix
- [#60](https://github.com/FlutterGen/flutter_gen/issues/60) Set files like .DS_Store to the ignore list.
> Release 1.3.1

- .gitignore
- Makefile
- example/pubspec.lock
- example/pubspec.yaml
- lib/src/flutter_generator.dart
- pubspec.lock
- pubspec.yaml
- test/assets_gen_integrations_test.dart
- test/assets_gen_test.dart
- test/colors_gen_test.dart
- test/flutter_gen_test.dart
- test/fonts_gen_test.dart
- test/gen_test_helper.dart
> Refactor tests

- .gitignore
- Makefile
- pubspec.lock
- pubspec.yaml
- revert to use test_coverage
- Pass CodeCov
> chore: revert to test_coverage

- README.md
- _internal/lib/src/pubspec.dart
- _internal/lib/src/pubspec.g.dart
- lib/src/flutter_generator.dart
- lib/src/settings/config.dart
- lib/src/settings/pubspec.dart
- lib/src/settings/pubspec.g.dart
- test/flutter_gen_test.dart
- test_resources/pubspec_generation_disabled.yaml
> Add option to enable/disable generation

- CHANGELOG.md
- README.md
- packages/command/pubspec.yaml
- packages/core/pubspec.yaml
- packages/runner/pubspec.yaml
- Document update.
- Pass CI after v2 release.
> chore(*) FlutterGen v2 release

- example/pubspec.lock
- example/pubspec.yaml
- packages/command/pubspec.lock
- packages/command/pubspec.yaml
- packages/core/pubspec.yaml
- packages/runner/pubspec.lock
- packages/runner/pubspec.yaml
> Fix conflicts

- example/lib/gen/assets.gen.dart
- packages/core/lib/generators/assets_generator.dart
- packages/core/test/gen_test_helper.dart
- packages/core/test_resources/actual_data/assets.gen.dart
- packages/core/test_resources/actual_data/assets_camel_case.gen.dart
- packages/core/test_resources/actual_data/assets_disable_null_safety.gen.dart
- packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
- packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_snake_case.gen.dart
- packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
Since AssetImage has assetName field.
CI Pass
> refactor: avoid generating duplicate assetName field

- .fvm/fvm_config.json
- .github/workflows/dart-ci.yaml
- .gitignore
- CHANGELOG.md
- Makefile
- example/pubspec.lock
- packages/command/pubspec.lock
- packages/command/pubspec.yaml
- packages/core/pubspec.yaml
- packages/runner/pubspec.lock
- packages/runner/pubspec.yaml
New Feature  
- [#98](https://github.com/FlutterGen/flutter_gen/pull/98) Support for adding assets from a package  
- Pass CI
> Release v3.1.0

- CHANGELOG.md
- packages/command/pubspec.lock
- packages/command/pubspec.yaml
- packages/core/pubspec.yaml
- packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
- packages/runner/pubspec.lock
- packages/runner/pubspec.yaml
> chore(release): bump up 3.1.1

- .fvm/fvm_config.json
> build: update flutter to 2.2.0

- .fvm/fvm_config.json
- .github/workflows/dart-ci.yaml
- .github/workflows/release.yaml
- .tool-versions
- Makefile
Replase [FVM](https://github.com/leoafarias/fvm) to [asdf](https://github.com/asdf-vm/asdf).
> build: replase to asdf

- example/.dart_tool/build/entrypoint/build.dart
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/pubspec.lock
- example/pubspec.yaml
- packages/command/pubspec.yaml
- packages/core/pubspec.lock
- packages/core/pubspec.yaml
- packages/runner/pubspec.yaml
> chore: update dependencies

- packages/core/lib/flutter_generator.dart
- packages/core/lib/settings/config.dart
- packages/core/lib/settings/pubspec.dart
- packages/core/lib/settings/pubspec.g.dart
- packages/core/test/assets_gen_integrations_test.dart
- packages/core/test/assets_gen_test.dart
- packages/core/test/colors_gen_test.dart
- packages/core/test/config_test.dart
- packages/core/test/fonts_gen_test.dart
- packages/core/test/gen_test_helper.dart
- Delete `lineLength` param.
-  use `line_length`.
> refactor: delete deprecated params

- .vscode/launch.json
- .vscode/settings.json
> build: add vscode settings

- example/pubspec.lock
- example/pubspec.yaml
- melos.yaml
- packages/command/pubspec.lock
- packages/core/pubspec.lock
- packages/core/pubspec.yaml
- packages/runner/pubspec.lock
> chore: Upgrade dependencies

- example/.dart_tool/build/entrypoint/build.dart
- example/android/build.gradle
- example/lib/json_serializable_sample.dart
- example/lib/json_serializable_sample.g.dart
- example/pubspec.lock
- example/pubspec.yaml
- packages/command/pubspec.lock
- packages/core/pubspec.lock
- packages/core/pubspec.yaml
- packages/runner/pubspec.lock
- Update dependency json_serializable `'>=5.0.0 <6.0.0'` -> `'>=5.0.0 <7.0.0'`
> chore: update json_serializable and add to example code

- .github/workflows/dart-ci.yaml
- melos.yaml
- packages/command/analysis_options.yaml
- packages/core/analysis_options.yaml
- packages/runner/analysis_options.yaml
Fix
- ignore analyzing each package example
- error on windows
- melos 1.0.0
> chore: fix ci

- example/ios/Flutter/Debug.xcconfig
- example/ios/Flutter/Release.xcconfig
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcworkspace/contents.xcworkspacedata
- example/pubspec.yaml
- example_resources/pubspec.yaml
- packages/command/pubspec.yaml
- packages/core/pubspec.yaml
- packages/runner/pubspec.yaml
- Update requires a min SDK version.
> refactor: update dependencies

- example/lib/gen/assets.gen.dart
- example_resources/lib/gen/assets.gen.dart
- packages/core/test_resources/actual_data/assets.gen.dart
- packages/core/test_resources/actual_data/assets_camel_case.gen.dart
- packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
- packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
- packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_snake_case.gen.dart
- packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
> fix: fix test for scale bug fix

- example/lib/gen/assets.gen.dart
- example_resources/lib/gen/assets.gen.dart
- packages/core/lib/generators/assets_generator.dart
- packages/core/test_resources/actual_data/assets.gen.dart
- packages/core/test_resources/actual_data/assets_camel_case.gen.dart
- packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
- packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
- packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_snake_case.gen.dart
- packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
Added keyName asset generate files.
related #248 #251
> feat: add keyName to asset generator

- .github/workflows/release.yaml
Run: https://github.com/FlutterGen/homebrew-tap/blob/master/.github/workflows/update_tap.yaml
> feat: auto update fluttergen to homebrew formula

- example/lib/gen/assets.gen.dart
- packages/core/lib/generators/assets_generator.dart
- packages/core/test_resources/actual_data/assets.gen.dart
- packages/core/test_resources/actual_data/assets_camel_case.gen.dart
- packages/core/test_resources/actual_data/assets_change_class_name.gen.dart
- packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_package_exclude_files.gen.dart
- packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
- packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_snake_case.gen.dart
- packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
- packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
Autogenerate List with assets in class
- #186 
- #270
> feat: add an asset list variable in class

- README.md
Adds a new section to the README with known issues. The first known issue added here is how to handle build errors when using the build runner with a custom build.yaml
Fixes #268  🎯
README only.
> Add known issue about using a build.yaml

- .github/workflows/build.yml
- melos.yaml
- scripts/codecov.sh
- scripts/coverage.sh
> Fix coverage scripts

- codecov.yaml
- packages/command/bin/flutter_gen_command.dart
- packages/command/pubspec.yaml
- packages/command/test/flutter_gen_command_test.dart
- Added some test codes for packages/command.
> test: command test with test_process

- CONTRIBUTING.md
> Specify Melos 2.9.0 in contribution instructions

- packages/core/lib/generators/assets_generator.dart
Update pubspec deprecation messages from `fluttergen` to `flutter_gen`.
> 📝 `fluttergen` -> `flutter_gen`

- .github/CODEOWNERS
- .github/FUNDING.yml
> chore: Add some maintainers

- README.md
> Fixes the `exclude` option descriptions in the README

- .github/workflows/release.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #<issue_number_goes_here> 🎯
> chore: Add permission for ci

- .gitignore
- .idea/.gitignore
- examples/example/example.iml
- examples/example_resources/example_resources.iml
- fluttergen.iml
- packages/command/flutter_gen.iml
- packages/core/flutter_gen_core.iml
- packages/core/lib/settings/asset_type.dart
- packages/core/lib/settings/color_path.dart
- packages/core/pubspec.yaml
- packages/runner/flutter_gen_runner.iml
Fixes https://github.com/FlutterGen/flutter_gen/issues/579 🎯
Also update ignored files for better development experiences.
> ⬆️ Allows `mime: '>=1.0.0 <3.0.0'`

- packages/core/lib/flutter_generator.dart
- packages/core/lib/generators/assets_generator.dart
- packages/core/lib/generators/integrations/integration.dart
- packages/core/test/gen_test_helper.dart
Prepare for integrations like zipped flare support.
> ♻️ Make `Integration.isSupported` as a possible future

- README.md
Commit 27282111af108044c44b254028bf633d7eb5adb6 moved the `colors.xml` file. This PR adjusts sources to changes.
> docs: update `colors.xml` reference

- .github/workflows/build.yml
- .github/workflows/release.yml
- .tool-versions
https://github.com/FlutterGen/flutter_gen/actions/runs/12722480428/job/35466548058
> 🔥 Not setup Dart explicitly for tools
