.gitattributes
.github/workflows/flutter-ci.yml
example/lib/gen/assets.gen.dart
example/lib/gen/colors.gen.dart
lib/src/generators/colors_generator.dart
lib/src/generators/fonts_generator.dart
lib/src/settings/asset_type.dart
lib/src/settings/color_path.dart
test_resources/actual_data/assets.gen.dart
test_resources/actual_data/assets_no_integrations.gen.dart
test_resources/actual_data/colors.gen.dart

Generate sorted statements
CI Pass

Generate sorted statements

---

.github/workflows/flutter-ci.yml
Makefile
example/pubspec.lock
lib/flutter_generator.dart
lib/src/generators/assets_generator.dart
lib/src/generators/generator_helper.dart
lib/src/settings/flutter_gen.dart
lib/src/utils/camel_case.dart
test/flutter_gen_test.dart

- https://github.com/FlutterGen/flutter_gen/issues/25 Support Windows.
- Pass CI on Windows.

Support windows

---

.github/workflows/release.yaml

- Auto release to pub.dev
- Pass CI

Auto release to pub.dev

---

CHANGELOG.md
pubspec.yaml

Bug fix
- Generate sorted statements [#27](https://github.com/FlutterGen/flutter_gen/pull/27)
- Make Windows work properly [#28](https://github.com/FlutterGen/flutter_gen/pull/28) 
- Pass CI

bump up to 1.0.2

---

.gitignore
README.md
example/assets/color/colors.xml
example/lib/gen/colors.gen.dart
lib/src/generators/colors_generator.dart
lib/src/utils/color.dart
pubspec.lock
pubspec.yaml
test_resources/actual_data/colors.gen.dart
test_resources/assets/color/colors.xml

Support generating MaterialAccentColor.
Related: #39 
CI pass

Support MaterialAccentColor

---

example/lib/gen/assets.gen.dart
example/lib/main.dart
example/pubspec.lock
lib/src/generators/assets_generator.dart
lib/src/generators/integrations/svg_integration.dart
test_resources/actual_data/assets.gen.dart
test_resources/actual_data/assets_camel_case.gen.dart
test_resources/actual_data/assets_no_integrations.gen.dart
test_resources/actual_data/assets_snake_case.gen.dart

Add support to specify a Key for convenience methods image() and svg().
Clients who need to assign a key to the Image or SvgPicture could use the convenience methods like Assets.images.my_image.image(key: Key("mykey")), rather than forcing them to do something like Image(key: Key("mykey"), Assets.images.my_image).

Added support for Key parameter in image() and svg()

---

CHANGELOG.md
pubspec.yaml

New Feature
- [#46](https://github.com/FlutterGen/flutter_gen/issues/46) Added support for unknown mime type files.
- Added support for [Rive (previously Flare)](https://rive.app/) files.
Pass CI

Release 1.3.0

---

.github/workflows/dart-ci.yaml
lib/src/generators/assets_generator.dart
lib/src/settings/asset_type.dart
test_resources/actual_data/assets.gen.dart
test_resources/actual_data/assets_camel_case.gen.dart
test_resources/actual_data/assets_snake_case.gen.dart

Append extension to name if file basename is not unique

---

packages/core/lib/generators/generator_helper.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_camel_case.gen.dart
packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
packages/core/test_resources/actual_data/assets_snake_case.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
packages/core/test_resources/actual_data/colors.gen.dart
packages/core/test_resources/actual_data/fonts.gen.dart

Fixed: Issue #75 
**MEMO**
If when forgot to add `--no-sound-null-safety` argument,
```
Xcode's output:
↳
lib/gen/assets.gen.dart:1:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.10
^^^^^^^^^^^^^^^
lib/gen/colors.gen.dart:1:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.10
^^^^^^^^^^^^^^^
lib/gen/fonts.gen.dart:1:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.10
```
- Pass CI

chore(generator): workaround nnbd #75

---

example/lib/gen/assets.gen.dart
example/pubspec.lock
packages/command/pubspec.lock
packages/command/pubspec.yaml
packages/core/lib/flutter_generator.dart
packages/core/lib/generators/assets_generator.dart
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/lib/settings/config.dart
packages/core/lib/settings/pubspec.dart
packages/core/lib/settings/pubspec.g.dart
packages/core/test/assets_gen_integrations_test.dart
packages/core/test/assets_gen_test.dart
packages/core/test/gen_test_helper.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_camel_case.gen.dart
packages/core/test_resources/actual_data/assets_disable_null_safety.gen.dart
packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
packages/core/test_resources/actual_data/assets_snake_case.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
packages/runner/pubspec.lock
packages/runner/pubspec.yaml

Fix: #50 
Set `package` argument for `AssetGenImage` and `SvgGenImage`
TODO:
Add package to flareActor after https://github.com/2d-inc/Flare-Flutter/issues/171 resolved
```dart
// AssetGenImage:
const AssetGenImage(String assetName)
: _assetName = assetName,
super(assetName, package: 'example');
// SvgGenImage:
SvgPicture svg({
String? package = 'example',
...
})
```
CI Pass

Support for adding assets from a package

---

CHANGELOG.md
example/pubspec.lock
example/pubspec.yaml
packages/command/pubspec.lock
packages/command/pubspec.yaml
packages/core/pubspec.yaml
packages/runner/pubspec.lock
packages/runner/pubspec.yaml

- [#117](https://github.com/FlutterGen/flutter_gen/issues/117) Update to analyzer 2.0.0.  
#121 
```yaml
dependency_overrides:
meta: ^1.7.0
```
- [#110](https://github.com/FlutterGen/flutter_gen/pull/110) Replace null safety dart style package.

chore: release 3.1.2

---

example/analysis_options.yaml
example/lib/gen/assets.gen.dart
example/lib/gen/colors.gen.dart
example/lib/gen/fonts.gen.dart
example/lib/main.dart
example/pubspec.lock
example/pubspec.yaml
packages/core/lib/generators/assets_generator.dart
packages/core/lib/generators/colors_generator.dart
packages/core/lib/generators/fonts_generator.dart
packages/core/lib/generators/generator_helper.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_camel_case.gen.dart
packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_snake_case.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
packages/core/test_resources/actual_data/colors.gen.dart
packages/core/test_resources/actual_data/fonts.gen.dart

- Add `directives_ordering` each `*.gen.dart` for not using `analysis_options.yaml`.

refactor: add directives_ordering for analysis

---

packages/core/lib/generators/assets_generator.dart

What's wrong:
_Statement.toDartDocString generates different strings on Windows and Ubuntu.
It causes changes in git if file was initially generated on Ubuntu, then checked out on Windows.
Ubuntu:    /// File path: assets/images/state/empty_state_new_space_black.svg
Windows: /// File path: assets\images\state\empty_state_new_space_black.svg
Fix: Write Linux-style path on Windows too.

Fix: _Statement.toDartDocString generates different strings on Windows and Ubuntu.

---

CHANGELOG.md
example/pubspec.lock
packages/command/pubspec.lock
packages/command/pubspec.yaml
packages/core/pubspec.yaml
packages/runner/pubspec.lock
packages/runner/pubspec.yaml

**Bug fix**
- [#156](https://github.com/FlutterGen/flutter_gen/pull/156) The Dartdocs generate different strings on Windows and Ubuntu.
**Features**
- [#157](https://github.com/FlutterGen/flutter_gen/pull/157) The supported version of json_serializable `>=5.0.0 <6.0.0` -> `>=5.0.0 <7.0.0`.

chore: release v4.1.1

---

README.md
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart

- expose `theme` parameter of `SvgPicture`
This is useful to specify svg's `currentColor` property recently supported by `flutter_svg`.
[SvgTheme class](https://pub.dev/documentation/flutter_svg/latest/flutter_svg/SvgTheme-class.html)

expose theme parameter of SvgPicture

---

README.md
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart

Add `cacheColorFilter` param of svg.
Related: #199

feat: add cacheColorFilter for svg

---

packages/core/lib/generators/generator_helper.dart

Currently all generated files with `flutter_gen` are included in the coverage report after run `flutter test --coverage`. With this PR the all generated files will include the `coverage:ignore-file` comment.

added coverage ignore comment on header

---

CHANGELOG.md
example/pubspec.yaml
example_resources/pubspec.yaml
packages/command/pubspec.yaml
packages/core/pubspec.yaml
packages/runner/pubspec.yaml

**Bug fix**
- [#236](https://github.com/FlutterGen/flutter_gen/issues/236) The crypto package 3.0.2 conflict in flutter_gen_runner 4.2.0 with integration_test.

chore: bump up to v4.2.1

---

.vscode/launch.json
example/ios/Podfile.lock
example/lib/gen/assets.gen.dart
example/lib/main.dart
packages/core/lib/generators/assets_generator.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_camel_case.gen.dart
packages/core/test_resources/actual_data/assets_change_class_name.gen.dart
packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
packages/core/test_resources/actual_data/assets_package_exclude_files.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart
packages/core/test_resources/actual_data/assets_snake_case.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart

Before #291 
Add support for an ImageProvider function.
- #235

Support image provider

---

README.md
example/pubspec.yaml
packages/core/lib/generators/assets_generator.dart
packages/core/lib/settings/config.dart
packages/core/lib/settings/pubspec.dart
packages/core/lib/settings/pubspec.g.dart
packages/core/test_resources/pubspec_assets_camel_case.yaml
packages/core/test_resources/pubspec_assets_package_parameter.yaml
packages/core/test_resources/pubspec_assets_package_parameter_disable_null_safety.yaml
packages/core/test_resources/pubspec_assets_snake_case.yaml

Moved style and package_parameter_enabled settings from asset to under assets.outputs.
**now**
```yaml
flutter_gen:
assets:
enabled: true
package_parameter_enabled: true
style: snake-case
outputs:
class_name: MyAssets
```
**`v5.0.0` or later.**
```yaml
flutter_gen:
assets:
enabled: true
outputs:
class_name: MyAssets
package_parameter_enabled: true
style: snake-case
```
**Warning message**

refactor: moved style and package_parameter_enabled to under assets.outputs.

---

example/lib/gen/assets.gen.dart
example_resources/lib/gen/assets.gen.dart
packages/core/lib/generators/integrations/lottie_integration.dart
packages/core/test_resources/actual_data/assets_lottie_integrations.gen.dart

fix: set controller to lottie.asset.

---

example/lib/gen/assets.gen.dart
example/lib/main.dart
example_resources/lib/gen/assets.gen.dart
packages/core/lib/generators/integrations/flare_integration.dart
packages/core/lib/generators/integrations/lottie_integration.dart
packages/core/lib/generators/integrations/rive_integration.dart
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/test/colors_gen_test.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
packages/core/test_resources/actual_data/assets_lottie_integrations.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart

Fixes #322 🎯
Change to `asset.gen.dart` same properties.
**When package_parameter_enabled = `true`**
```dart
String get path => _assetName;
String get keyName => 'packages/$packageName/\$_assetName';
```
**When package_parameter_enabled  = `false`**
```dart
String get path => _assetName;
String get keyName => _assetName;
```

feat: add keyName to integrations 

---

examples/example/lib/freezed_sample.freezed.dart
examples/example/lib/gen/assets.gen.dart
examples/example/lib/gen/colors.gen.dart
examples/example/lib/gen/fonts.gen.dart
examples/example/lib/json_serializable_sample.dart
examples/example/macos/Flutter/GeneratedPluginRegistrant.swift
examples/example/pubspec.yaml
examples/example_resources/lib/gen/assets.gen.dart
examples/example_resources/lib/gen/colors.gen.dart
examples/example_resources/pubspec.yaml
packages/core/lib/generators/generator_helper.dart
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_camel_case.gen.dart
packages/core/test_resources/actual_data/assets_change_class_name.gen.dart
packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
packages/core/test_resources/actual_data/assets_ignore_files.gen.dart
packages/core/test_resources/actual_data/assets_lottie_integrations.gen.dart
packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
packages/core/test_resources/actual_data/assets_package_exclude_files.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart
packages/core/test_resources/actual_data/assets_snake_case.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
packages/core/test_resources/actual_data/assets_unknown_mime_type.gen.dart
packages/core/test_resources/actual_data/colors.gen.dart
packages/core/test_resources/actual_data/colors_change_class_name.gen.dart
packages/core/test_resources/actual_data/fonts.gen.dart
packages/core/test_resources/actual_data/fonts_change_class_name.gen.dart

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #<issue_number_goes_here> 🎯

feat: support flutter_svg 2.0.0

---

packages/core/lib/generators/assets_generator.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/pubspec_assets_package_parameter.yaml

This change ensures that when `packageParameterEnabled` is enabled, assets with unknown mime type, for which only the asset key is generated, can be resolved from outside of the containing package.

When `packageParameterEnabled` is enabled, include the package name for path assets

---

.github/PULL_REQUEST_TEMPLATE.md

Minor tweak to PULL_REQUEST_TEMPLATE to fix melos command. The old command doesn't exist, and this one seems to do what was intended.

Update PULL_REQUEST_TEMPLATE.md to fix melos command

---

packages/core/lib/generators/assets_generator.dart
packages/core/test_resources/actual_data/assets_camel_case.gen.dart
packages/core/test_resources/actual_data/assets_snake_case.gen.dart

Allowed the generated values statement to optionally be static. For flat listings, each asset is `static` but the `values` property is not, making it inaccessible. Now when generating flat listings, values is static like all the other assets.
Fixes #415 🎯

Allowed the generated `values` statement to optionally be static. Fixes #415

---

.gitignore
.idea/modules.xml
melos.yaml

Helps the startup from IntelliJ editors.

🔧 [IntelliJ] Fix module configurations

---

examples/example/lib/gen/assets.gen.dart
examples/example/pubspec.yaml
packages/core/lib/generators/assets_generator.dart
packages/core/test_resources/CHANGELOG.md
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/pubspec_assets.yaml

Assets under the root directory are not handled before.
Fixes #69 🎯

🐛 Handles root directory assets

---

packages/core/lib/generators/assets_generator.dart
packages/core/lib/settings/asset_type.dart
packages/core/lib/utils/identifer.dart
packages/core/lib/utils/string.dart
packages/core/test/assets_gen_test.dart

Changed `AssetTypeIsUniqueWithoutExtension` to more robustly pick valid unique names for each asset.
The strategy is as follows:
1) Convert the asset file name, to a valid dart identifier, that is
- Replace non ASCII chars with ASCII.
- Ensure the name starts with a letter (not number or _).
- Style the name per the camelCase or snakeCase rules.
2) Use the asset name without extension. If unique and not a dart reserved word use that.
3) Use the asset name with extension. If unique and not a dart reserved word use that.
4) If there are any collisions, append a underscore suffix to each item until they are unique.
This will now handle a wide-range of names that weren't previously supported. Dart identifiers, assets starting with numbers, asserts with non-ascii characters, assets with …

More robustly pick valid unique names for each asset.

---

examples/example/lib/gen/assets.gen.dart
packages/core/lib/generators/integrations/rive_integration.dart
packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart

Add support for 'useArtboardSize' argument in rive integration
Fixes #486 🎯

Add support for 'useArtboardSize' argument in rive integration

---

examples/example/lib/gen/assets.gen.dart
examples/example_resources/lib/gen/assets.gen.dart
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/lib/settings/pubspec.g.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_directory_path.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_parse_metadata.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart
packages/runner/example/lib/gen/assets.gen.dart

Since version 5.5.0+1, the SvgTheme no longer works. It doesn't work because flutter_svg has deprecated using the `theme` with the `SvgPicture` constructor, and suggests that you pass the theme to the bytes loader instead.
Fixes #531  🎯

fix: provide theme to SvgAssetLoader instead of SvgPicture

---

examples/example/lib/gen/assets.gen.dart
examples/example_resources/lib/gen/assets.gen.dart
packages/core/lib/generators/assets_generator.dart
packages/core/lib/generators/generator_helper.dart
packages/core/lib/generators/integrations/flare_integration.dart
packages/core/lib/generators/integrations/image_integration.dart
packages/core/lib/generators/integrations/integration.dart
packages/core/lib/generators/integrations/lottie_integration.dart
packages/core/lib/generators/integrations/rive_integration.dart
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/lib/settings/import.dart
packages/core/pubspec.yaml
packages/core/test/assets_gen_integrations_test.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_directory_path.gen.dart
packages/core/test_resources/actual_data/assets_flare_integrations.gen.dart
packages/core/test_resources/actual_data/assets_flavored.gen.dart
packages/core/test_resources/actual_data/assets_lottie_integrations.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_parse_metadata.gen.dart
packages/core/test_resources/actual_data/assets_rive_integrations.gen.dart
packages/core/test_resources/actual_data/assets_svg_integrations.gen.dart

✨ Add `Import` abstraction for package imports alias

---

README.md

Add asdf and GitHub Actions installations on README.
- [FlutterGen/asdf-fluttergen](https://github.com/FlutterGen/asdf-fluttergen)
- [FlutterGen/setup-fluttergen](https://github.com/FlutterGen/setup-fluttergen)

docs: add asdf and GitHub Actions installations

---

examples/example/test/svg_integrations_test.dart
melos.yaml
packages/core/test/assets_gen_integrations_test.dart
packages/core/test/assets_gen_test.dart
packages/core/test/colors_gen_test.dart
packages/core/test/flutter_gen_test.dart
packages/core/test/fonts_gen_test.dart
packages/core/test/gen_test_helper.dart

I limited concurrent execution because these logs were being output during the execution of the flutter command.
When `melos run get`
```
ERROR: ERROR: [example]: Waiting for another flutter command to release the startup lock...
ERROR: ERROR: [flutter_gen]: Waiting for another flutter command to release the startup lock...
ERROR: ERROR: [flutter_gen_runner]: Waiting for another flutter command to release the startup lock...
```
And fix analyze.

chore: fix concurrency execute with melos.

---

examples/example/lib/gen/assets.gen.dart
examples/example_resources/lib/gen/assets.gen.dart
packages/command/example/lib/gen/assets.gen.dart
packages/core/example/lib/gen/assets.gen.dart
packages/core/lib/generators/integrations/image_integration.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_camel_case.gen.dart
packages/core/test_resources/actual_data/assets_change_class_name.gen.dart
packages/core/test_resources/actual_data/assets_directory_path.gen.dart
packages/core/test_resources/actual_data/assets_flavored.gen.dart
packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
packages/core/test_resources/actual_data/assets_package_exclude_files.gen.dart
packages/core/test_resources/actual_data/assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_parse_metadata.gen.dart
packages/core/test_resources/actual_data/assets_snake_case.gen.dart
packages/runner/example/lib/gen/assets.gen.dart

Image assets are finalized during builds, they cannot be changed during the runtime. The `gaplessPlayback` defaults to `false` which might lead to images flashing between routes when the provider changes, which it doesn't in fact.
Now we change it to `true` to ignore changes to provide a good display experience. This can also considered as a non-breaking change in most cases.

⚡️ Enables `gaplessPlayback` by default for image assets

---

README.md
packages/core/lib/flutter_generator.dart
packages/core/lib/generators/fonts_generator.dart
packages/core/lib/settings/pubspec.dart
packages/core/lib/settings/pubspec.g.dart
packages/core/test/fonts_gen_test.dart
packages/core/test/gen_test_helper.dart
packages/core/test_resources/actual_data/fonts_package_parameter.gen.dart
packages/core/test_resources/pubspec_fonts_package_parameter.yaml

Fixes #357 🎯
Parse `package_parameter_enabled` for the fonts property and add a `package` accessor to the generated font class.
```dart
class MyFonts {
MyFonts._();
static const String package = 'design_system';
/// Font family: Arial Black
static const String arialBlack = 'packages/$package/Arial Black';
/// Font family: Calibri
static const String calibri = 'packages/$package/Calibri';
}
```

feat: handle package name for fonts

---

README.md
packages/command/test/flutter_gen_command_test.dart
packages/core/lib/settings/config.dart
packages/core/test/assets_gen_test.dart
packages/core/test_resources/build_assets.yaml
packages/core/test_resources/build_runner_assets.yaml

Fixes #589 🎯
change builder name to flutter_gen_runner

fix: change builder name to flutter_gen_runner (#589)

---

packages/command/bin/flutter_gen_command.dart
packages/command/test/flutter_gen_command_test.dart
packages/core/lib/flutter_generator.dart
packages/core/lib/settings/config.dart
packages/core/lib/utils/version.dart
packages/core/test/assets_gen_test.dart
packages/core/test_resources/actual_data/build_assets.gen.dart
packages/core/test_resources/actual_data/build_empty.gen.dart
packages/core/test_resources/actual_data/build_runner_assets.gen.dart
packages/core/test_resources/build_empty.yaml
packages/core/test_resources/build_runner_assets.yaml

- Addresses https://github.com/FlutterGen/flutter_gen/pull/592#issuecomment-2424750703
- Make logs prettier

🔊 Better stdouts

---

analysis_options.yaml
examples/example/lib/main.dart
melos.yaml
packages/core/lib/flutter_generator.dart
packages/core/lib/settings/asset_type.dart
packages/core/test/assets_gen_test.dart
packages/core/test/colors_gen_test.dart
packages/core/test/fonts_gen_test.dart
packages/core/test/gen_test_helper.dart

⚡️ Format Dart files with the current Dart version instead of the latest supported

---

packages/core/lib/generators/integrations/lottie_integration.dart
packages/core/pubspec.yaml

⬆️ Support `package:archive` v4

---

README.md
packages/core/lib/generators/assets_generator.dart
packages/core/lib/settings/config_default.dart
packages/core/lib/settings/pubspec.dart
packages/core/lib/settings/pubspec.g.dart
packages/core/test/assets_gen_integrations_test.dart
packages/core/test_resources/actual_data/assets_no_image_integration.gen.dart
packages/core/test_resources/pubspec_assets_no_image_integration.yaml

Adds the explicit and configurable image integration.
Resolves #636 🎯

✨ Allows not enable the image integration

---

packages/core/pubspec.yaml

An alternative of #652.
Fixes #651 🎯

Contraints `dart_style` to `>=2.3.7`

---

README.md
examples/example/lib/gen/assets.gen.dart
examples/example/pubspec.yaml
examples/example_resources/lib/gen/assets.gen.dart
examples/example_resources/pubspec.yaml
packages/core/lib/generators/integrations/lottie_integration.dart
packages/core/test_resources/actual_data/assets.gen.dart
packages/core/test_resources/actual_data/assets_lottie_integrations.gen.dart
packages/core/test_resources/actual_data/assets_no_integrations.gen.dart
packages/core/test_resources/actual_data/build_assets.gen.dart

- This MR will add missing parameters in Lottie Integration from [lottie's release 3.0.0](https://github.com/xvrh/lottie-flutter/releases/tag/v3.0.0)
- chore: I also updated actual test data after running test

Add missing parameters in Lottie integration from lottie 3.0.0

---

packages/command/pubspec.yaml
packages/core/pubspec.yaml
packages/runner/pubspec.yaml
pubspec.yaml

dart_style v2.3.7 requries dart 3.0.0 or higher.
https://pub.dev/packages/dart_style/versions
Fixes #651 🎯

feat: Update required dart version

---

.github/workflows/release.yml

https://github.com/FlutterGen/flutter_gen/actions/runs/13612602409/job/38051634384
Related to https://github.com/actions/upload-artifact/issues/480
Also allows manual dispatch.

💚 Fix artifacts release

---

.github/workflows/build.yml
examples/example/lib/gen/assets.gen.dart
examples/example/pubspec.yaml
examples/example_resources/lib/gen/assets.gen.dart
examples/example_resources/pubspec.yaml
melos.yaml
packages/command/pubspec.yaml
packages/core/lib/flutter_generator.dart
packages/core/lib/settings/config.dart
packages/core/lib/settings/pubspec.dart
packages/core/lib/settings/pubspec.g.dart
packages/core/lib/utils/formatter.dart
packages/core/lib/utils/identifer.dart
packages/core/pubspec.yaml
packages/core/test/assets_gen_test.dart
packages/core/test/colors_gen_test.dart
packages/core/test/fonts_gen_test.dart
packages/core/test/gen_test_helper.dart
packages/runner/lib/flutter_gen_runner.dart
packages/runner/pubspec.yaml
pubspec.yaml

Use the `dart_style` v3 to cover the short-style formatting of old projects.

⬆️ Constraint `dart_style` v3 which also bumps the SDK constraint to 3.4

---

examples/example/lib/gen/assets.gen.dart
examples/example_resources/lib/gen/assets.gen.dart
packages/core/lib/generators/integrations/svg_integration.dart
packages/core/test_resources/actual_data/assets_assets.gen.dart
packages/core/test_resources/actual_data/assets_assets_directory_path.gen.dart
packages/core/test_resources/actual_data/assets_assets_directory_path_with_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_assets_flavored.gen.dart
packages/core/test_resources/actual_data/assets_assets_package_parameter.gen.dart
packages/core/test_resources/actual_data/assets_assets_package_parameter_disable_null_safety.gen.dart
packages/core/test_resources/actual_data/assets_assets_parse_metadata.gen.dart
packages/core/test_resources/actual_data/assets_assets_svg_integrations.gen.dart
packages/core/test_resources/actual_data/assets_normal.gen.dart
packages/core/test_resources/actual_data/build_assets_build_assets.gen.dart
packages/core/test_resources/actual_data/build_assets_build_empty.gen.dart
packages/core/test_resources/actual_data/build_assets_build_runner_assets.gen.dart

Add possibility to specify color mapper for svg.
Fixes #679  🎯

Add svg ColorMapper to svg loader
